In [15]:
import numpy as np
import statsmodels.api as sm

In [16]:
rng = np.random.default_rng(987)

In [19]:
nobs = 100

X = rng.random((nobs,2))

X = sm.add_constant(X) # adds column of ones

X[:5]

array([[1.        , 0.01599711, 0.8209245 ],
       [1.        , 0.95030422, 0.00180159],
       [1.        , 0.57569728, 0.67148264],
       [1.        , 0.34051794, 0.65394525],
       [1.        , 0.71661607, 0.55723337]])

In [21]:
beta = [1, 0.1, 0.5]

e = rng.random(nobs)

In [22]:
y = np.dot(X, beta) + e

#### In mathematics, the dot product or scalar product is an algebraic operation that takes two equal-length sequences of numbers (usually coordinate vectors) and returns a single number. 

In [24]:
y.shape

(100,)

In [27]:
1+0.1*0.01599711+0.5*0.8209245


1.4120619609999998

In [30]:
np.dot(X, beta)[:5]

array([1.41206196, 1.09593122, 1.39331105, 1.36102442, 1.35027829])

In [32]:
# Fit regression model

model = sm.OLS(y,X)
result = model.fit()

In [34]:
result.params

array([1.47250528, 0.06578715, 0.58140033])

In [36]:
result.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                      y   R-squared:                       0.238
Model:                            OLS   Adj. R-squared:                  0.223
Method:                 Least Squares   F-statistic:                     15.17
Date:                Thu, 23 Jul 2020   Prob (F-statistic):           1.85e-06
Time:                        22:56:57   Log-Likelihood:                -14.980
No. Observations:                 100   AIC:                             35.96
Df Residuals:                      97   BIC:                             43.78
Df Model:                           2                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const          1.4725      0.083     17.786      0.000       1.308       1.637
x1             0.0658      0.097      0.676      0.500      -0.127       0.259
x2             0.5814      0.106      5.500      0.000       0.372       0.791
==============================================================================
Omnibus:                       19.534   Durbin-Watson:                   1.758
Prob(Omnibus):                  0.000   Jarque-Bera (JB):                5.581
Skew:                           0.224   Prob(JB):                       0.0614
Kurtosis:                       1.933   Cond. No.                         5.82
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [37]:
dir(result)

['HC0_se',
 'HC1_se',
 'HC2_se',
 'HC3_se',
 '_HCCM',
 '__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_cache',
 '_data_attr',
 '_get_robustcov_results',
 '_is_nested',
 '_use_t',
 '_wexog_singular_values',
 'aic',
 'bic',
 'bse',
 'centered_tss',
 'compare_f_test',
 'compare_lm_test',
 'compare_lr_test',
 'condition_number',
 'conf_int',
 'conf_int_el',
 'cov_HC0',
 'cov_HC1',
 'cov_HC2',
 'cov_HC3',
 'cov_kwds',
 'cov_params',
 'cov_type',
 'df_model',
 'df_resid',
 'diagn',
 'eigenvals',
 'el_test',
 'ess',
 'f_pvalue',
 'f_test',
 'fittedvalues',
 'fvalue',
 'get_influence',
 'get_prediction',
 'get_robustcov_results',
 'initialize',
 'k_constant',
 'llf',
 'load',